### ISSUE TITLE
Error in KMS Section

### ISSUE THREAD

**Issue by GenAIGator** [mykter/aws-security-cert-study-guide#1]
This below is incorrect, evaluation IS the same as standard IAM logic.  If they key policy doesn't deny and the IAM policy allows, its allowed, even if the key policy doesn't specifically allow it.

> KMS
> Key policies
> Required. Also different evaluation logic to standard IAM - if the key policy doesn't allow, then the request is denied regardless of identity policies.

**Comment by mykter** [comment]
Thanks! I assume I was thinking of how KMS is different to most other services in that the key policy is required.
Welcome to github and good luck with the cert (if you're planning on taking it)!

**Comment by GenAIGator** [comment]
> Thanks! I assume I was thinking of how KMS is different to most other services in that the key policy is required.
> Welcome to github and good luck with the cert (if you're planning on taking it)!

My pleasure, thanks for making the guide, its very helpful, I plan on taking the exam next month.

**Comment by GenAIGator** [comment]
Upon futher research you were originally correct.

To further clarify:
If they key policy allows root full KMS access (which is always in the key policy by default), IAM for KMS is enabled and allowed.

However if you edit the key policy and disable root's full KMS access from the policy, then any IAM allow permissions for KMS will not apply and the KMS policy will control access with an implicit deny for anything not specifically allowed (an explicit deny somewhere else will presumably override this, as well as not having an allow in the Org's SCP policy).
